@IsTest
public class CodeKnacker {


	static testMethod void test() {
		Test.startTest();
		CodeKnack testObj = new CodeKnack();
        CodeKnack1 testobj1=new CodeKnack1();
		CodeKnack2 testObj2 = new CodeKnack2();
		CodeKnack3 testObj3 = new CodeKnack3();
		CodeKnack4 testObj4 = new CodeKnack4();
		CodeKnack5 testObj5 = new CodeKnack5();
		Test.stopTest();
		System.assertNotEquals(1, 0);
	}


}