<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="12.3px" height="12.4px" viewBox="0 0 12.3 12.4" enable-background="new 0 0 12.3 12.4" xml:space="preserve">
<polygon fill="#999999" points="6.8,6.2 9.9,3 9.4,2.4 6.2,5.6 3,2.4 2.4,3 5.6,6.2 2.4,9.4 3,10 6.2,6.8 9.4,10 9.9,9.4 "/>
</svg>
