<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="40px" height="40px" viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve">
<polygon fill="#FFFFFF" points="37.4,11 32.7,6.3 15.3,23.7 7.3,15.7 2.6,20.4 10.6,28.4 10.6,28.4 15.3,33.1 20,28.4 20,28.4 "/>
</svg>
